debug: false


server:
  port: 9000
  servlet:
    context-path: /api

spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

  messages:
    fallback-to-system-locale: false
    basename: messages,config.i18n.messages
  application:
    name: Capsule
  main:
    log-startup-info: false
    banner-mode: off
  profiles:
    active: dev
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      fail-on-empty-beans: false

  datasource:
    url: jdbc:postgresql://localhost:5432/parchenegar
    username: nima
    password: 123456789

  jpa:
    properties:
      hibernate:
        ddl-auto: validate
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: capsule
        format_sql: true
    show-sql: true
    database: postgresql
    generate-ddl: false

logging:
  level:
    root: INFO

storage:
  location: /home/nima/uploads